# Time Series Dataset Analysis Configuration
# Following MIT Statistical Learning Standards

analysis:
  # Dataset characterization parameters
  dataset:
    auto_detect_date_column: true
    date_keywords: ['date', 'time', 'timestamp', 'datetime', 'year', 'month']
    numeric_precision: 6  # Decimal places for reporting

  # Missing data thresholds (MIT standards)
  missing_data:
    excellent_threshold: 0.01    # ρ < 1%
    acceptable_threshold: 0.05   # ρ < 5%
    concerning_threshold: 0.10   # ρ < 10%
    categories:
      excellent: "Minimal missing data (ρ < 1%)"
      acceptable: "Seldom missing data (1% ≤ ρ < 5%)"
      concerning: "Substantial missing data (5% ≤ ρ < 10%)"
      severe: "Critical missing data (ρ ≥ 10%)"

  # Temporal structure detection
  temporal:
    frequency_classifications:
      daily:
        min_days: 0.95
        max_days: 1.05
        code: "D"
      weekly:
        min_days: 6.5
        max_days: 7.5
        code: "W"
      monthly:
        min_days: 28
        max_days: 31
        code: "M"
      quarterly:
        min_days: 89
        max_days: 92
        code: "Q"
      annual:
        min_days: 365
        max_days: 366
        code: "Y"

    # Temporal gap detection (outlier threshold)
    gap_detection:
      sigma_threshold: 3.0  # Number of standard deviations
      min_gap_proportion: 0.01  # Report gaps if > 1% of observations

    # Regularity metrics
    regularity:
      excellent_threshold: 0.95  # CV < 5%
      acceptable_threshold: 0.90  # CV < 10%

  # Statistical analysis parameters
  statistics:
    # Confidence levels
    confidence_intervals:
      alpha: 0.05  # 95% confidence
      z_critical: 1.96

    # Normality testing (Jarque-Bera)
    normality:
      alpha: 0.05  # Significance level
      min_observations: 3  # Minimum sample size

    # Outlier detection (z-score method)
    outliers:
      threshold: 3.0  # |z| > 3 (3-sigma rule)
      method: "zscore"  # Options: zscore, iqr, isolation_forest

    # Distribution moments
    moments:
      compute_skewness: true
      compute_kurtosis: true
      compute_cv: true  # Coefficient of variation

  # Stationarity testing (Augmented Dickey-Fuller)
  stationarity:
    # ADF test parameters
    adf:
      max_lag: 10  # Maximum lag for ADF regression
      regression: "ct"  # Options: c (constant), ct (constant + trend), ctt (constant + linear + quadratic trend), nc (no constant)
      alpha: 0.05  # Significance level

    # Auto-lag selection methods
    autolag:
      method: "AIC"  # Options: AIC, BIC, t-stat
      max_lag_auto: null  # If null, use 12*(nobs/100)^(1/4)

  # Autocorrelation analysis
  autocorrelation:
    # ACF/PACF parameters
    default_nlags: 40  # Default number of lags
    max_nlags_proportion: 0.5  # Max lags as proportion of series length

    # Significance testing
    confidence_level: 0.95
    bartlett_correction: true  # Use Bartlett's formula for SE

    # Lag identification
    significant_lag_threshold: 1.96  # Critical value for 95% CI

  # Frequency domain analysis
  frequency_domain:
    # Fourier transform parameters
    fft:
      window: "hann"  # Window function: hann, hamming, blackman
      detrend: "linear"  # Detrending: none, constant, linear
      scaling: "density"  # PSD scaling: density, spectrum

    # Periodogram
    periodogram:
      method: "welch"  # Options: periodogram, welch
      nperseg: 256  # Segment length for Welch's method
      noverlap: null  # Overlap (default: nperseg // 2)

  # Visualization settings
  visualization:
    # Figure dimensions
    figure_size:
      width: 18
      height: 12
      dpi: 100

    # Style settings
    style: "whitegrid"  # seaborn style
    context: "notebook"  # plotting context
    palette: "deep"  # color palette

    # Plot types
    plots:
      missing_data_heatmap: true
      type_distribution: true
      completeness_bars: true
      time_series_lines: true
      distribution_histograms: true
      acf_plots: true
      pacf_plots: true
      qq_plots: true

    # Plot parameters
    histogram:
      bins: 50
      alpha: 0.7
      edgecolor: "black"

    line:
      linewidth: 1.5
      alpha: 0.7

  # Report generation
  reporting:
    # Output formats
    formats:
      - json
      - html
      - markdown

    # JSON output settings
    json:
      indent: 2
      sort_keys: false
      datetime_format: "iso"

    # Verbosity levels
    verbosity:
      minimal: 1  # Only key metrics
      standard: 2  # Standard analysis
      detailed: 3  # Full mathematical details
      debug: 4    # Include intermediate calculations

    # Summary statistics
    summary:
      include_formulas: true
      include_assumptions: true
      include_references: true

# Mathematical formulas and references
formulas:
  missing_data_rate: "ρ_missing = (Σ I(x_ij = NA)) / (n × p)"
  sampling_frequency: "f_s = 1 / Δt, where Δt = mode(t_i - t_{i-1})"
  nyquist_frequency: "f_N = f_s / 2"
  acf: "ρ(k) = Cov(y_t, y_{t-k}) / Var(y_t)"
  adf_regression: "Δy_t = α + βt + γy_{t-1} + Σ δ_i Δy_{t-i} + ε_t"
  jarque_bera: "JB = (n/6) * [S² + (K-3)²/4]"
  coefficient_variation: "CV = σ / μ"
  z_score: "z = (x - μ) / σ"

# Statistical assumptions and requirements
assumptions:
  stationarity:
    - "Constant mean over time: E[y_t] = μ"
    - "Constant variance over time: Var[y_t] = σ²"
    - "Autocovariance depends only on lag: Cov[y_t, y_{t+k}] = γ(k)"

  normality:
    - "Data follows normal distribution: X ~ N(μ, σ²)"
    - "Skewness ≈ 0, Kurtosis ≈ 3 (excess kurtosis ≈ 0)"

  independence:
    - "Observations are independent: Cov[ε_i, ε_j] = 0 for i ≠ j"
    - "No autocorrelation in residuals"

# References (MIT Statistical Learning Standards)
references:
  textbooks:
    - "Hastie, Tibshirani, Friedman: The Elements of Statistical Learning (2nd ed.)"
    - "Shumway & Stoffer: Time Series Analysis and Its Applications (4th ed.)"
    - "Hamilton: Time Series Analysis (1994)"
    - "Box, Jenkins, Reinsel: Time Series Analysis: Forecasting and Control (5th ed.)"

  papers:
    - "Dickey & Fuller (1979): Distribution of Estimators for Autoregressive Time Series"
    - "Jarque & Bera (1980): Efficient Tests for Normality, Homoscedasticity and Serial Independence"
    - "Kwiatkowski et al. (1992): Testing the Null Hypothesis of Stationarity (KPSS test)"
