# Finnhub Data Extraction Configuration
# API documentation: https://finnhub.io/docs/api

extraction:
  # Data source settings
  source:
    name: "Finnhub"
    api: "finnhub"
    base_url: "https://finnhub.io/api/v1"
    documentation_url: "https://finnhub.io/docs/api"

  # API authentication (credentials stored in .env)
  authentication:
    api_key_env: "FINNHUB_API_KEY"  # Read from .env file
    required: true
    auth_method: "query_param"  # API key passed as query parameter

  # Rate limiting (free tier)
  rate_limiting:
    enabled: true
    requests_per_minute: 60  # Free tier: 60 requests/minute
    requests_per_day: null   # No daily limit on free tier
    delay_between_requests: 1  # Seconds (safe: 60/60 = 1s)

    # Premium tier (if upgraded)
    premium:
      enabled: false
      requests_per_minute: 300
      requests_per_second: 30

  # Network reliability settings
  network:
    timeout_seconds: 30
    max_retries: 3
    retry_delay_seconds: 2
    exponential_backoff: true
    backoff_factor: 2.0

  # Data extraction parameters
  data:
    # Endpoint for stock candles (OHLCV data)
    endpoint: "/stock/candle"

    # Resolution (candle interval)
    resolution: "D"  # Options: 1, 5, 15, 30, 60, D, W, M (1=1min, D=daily, W=weekly, M=monthly)

    # OHLCV column mapping (Finnhub format)
    column_mapping:
      "o": "Open"      # Open prices
      "h": "High"      # High prices
      "l": "Low"       # Low prices
      "c": "Close"     # Close prices
      "v": "Volume"    # Volume
      "t": "timestamp" # Unix timestamp

    # Additional endpoints (optional)
    endpoints:
      quote: "/quote"                    # Real-time quote
      company_profile: "/stock/profile2" # Company profile
      news: "/company-news"              # Company news
      earnings: "/stock/earnings"        # Earnings data
      metrics: "/stock/metric"           # Company metrics

  # Cache configuration
  cache:
    enabled: true
    cache_hours: 24  # Cache validity
    storage_path: "data/raw"
    tolerance_days: 3
    auto_cleanup: true
    retention_days: 365

  # Quality checks
  quality_checks:
    enabled: true
    check_empty_data: true
    check_status: true  # Check API response status
    min_rows_required: 10

    # Data integrity
    integrity:
      check_missing_dates: true
      check_price_continuity: true
      max_missing_rate: 0.10
      validate_timestamps: true  # Ensure timestamps are valid

  # Error handling
  error_handling:
    on_fetch_failure: "skip"  # Options: skip, raise, retry
    on_rate_limit: "wait"  # Options: wait, skip, raise
    on_invalid_key: "raise"
    on_invalid_symbol: "warn"  # Options: warn, raise, skip
    log_errors: true
    error_log_path: "logs/finnhub_errors.log"

  # Response handling
  response:
    # Finnhub returns status 's' in response
    success_status: "ok"
    no_data_status: "no_data"

    # Convert Unix timestamps to datetime
    convert_timestamps: true
    timestamp_unit: "s"  # Seconds since epoch

# Logging
logging:
  level: "INFO"
  log_to_file: true
  log_file: "logs/finnhub_extraction.log"
  log_api_calls: true
  log_rate_limits: true
