#!/usr/bin/env python3
"""Generate a markdown runtime snapshot doc from live artifacts."""

from __future__ import annotations

import argparse
import json
import subprocess
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]


def _run_json(cmd: list[str]) -> dict[str, Any]:
    proc = subprocess.run(
        cmd,
        cwd=str(ROOT),
        capture_output=True,
        text=True,
        timeout=120.0,
    )
    if not proc.stdout.strip():
        raise RuntimeError(f"command returned no stdout: {' '.join(cmd)}")
    return json.loads(proc.stdout)


def _load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def build_snapshot(root: Path = ROOT) -> str:
    runtime = _run_json(["python", "scripts/project_runtime_status.py"])
    capital = _run_json(["python", "scripts/capital_readiness_check.py", "--json"])
    dashboard = _load_json(root / "visualizations" / "dashboard_data.json")
    watcher = _load_json(root / "logs" / "overnight_denominator" / "live_denominator_latest.json")
    gate_path = root / "logs" / "audit_gate" / "production_gate_latest.json"
    gate = _load_json(gate_path) if gate_path.exists() else {}
    now_utc = datetime.now(timezone.utc).replace(microsecond=0).isoformat()

    live_current = watcher.get("cycles", [])
    latest_cycle = live_current[-1] if live_current else {}
    meta = dashboard.get("meta", {})
    checks = dashboard.get("checks", [])

    lines = [
        "# Generated Runtime Status Snapshot",
        "",
        "Doc Type: status_snapshot",
        "Authority: generated from live artifacts; advisory only and not hand-edited",
        "Owner: Agent C",
        f"Last Verified: {now_utc[:10]}",
        "Verification Commands:",
        "- `python scripts/project_runtime_status.py`",
        "- `python scripts/capital_readiness_check.py --json`",
        "- `python scripts/render_runtime_doc_snapshot.py --output Documentation/GENERATED_RUNTIME_STATUS_SNAPSHOT.md`",
        "Artifacts:",
        "- `visualizations/dashboard_data.json`",
        "- `logs/overnight_denominator/live_denominator_latest.json`",
        "- `logs/audit_gate/production_gate_latest.json`",
        "Supersedes: none",
        "Expires When: regenerated by a newer runtime status snapshot",
        "Generated By: `scripts/render_runtime_doc_snapshot.py`",
        "",
        f"Generated At: {now_utc}",
        "",
        "## Runtime",
        "",
        f"- overall status: `{runtime.get('status')}`",
        f"- failed checks: `{', '.join(runtime.get('failed_checks', [])) or 'none'}`",
        "",
        "## Capital Readiness",
        "",
        f"- ready: `{str(capital.get('ready')).lower()}`",
        f"- verdict: `{capital.get('verdict')}`",
        f"- reasons: `{'; '.join(capital.get('reasons', [])) or 'none'}`",
        "",
        "## Production Gate",
        "",
        f"- phase3_ready: `{gate.get('phase3_ready')}`",
        f"- phase3_reason: `{gate.get('phase3_reason', gate.get('phase3_reason_code', 'unknown'))}`",
        "",
        "## Dashboard Truth",
        "",
        f"- data_origin: `{meta.get('data_origin')}`",
        f"- payload_schema_version: `{meta.get('payload_schema_version')}`",
        f"- positions_stale: `{dashboard.get('positions_stale')}`",
        f"- positions_source: `{dashboard.get('positions_source')}`",
        f"- performance_unknown: `{dashboard.get('performance_unknown')}`",
        f"- checks: `{'; '.join(checks) or 'none'}`",
        "",
        "## Live Denominator",
        "",
        f"- fresh_trade_rows: `{latest_cycle.get('fresh_trade_rows')}`",
        f"- fresh_linkage_included: `{latest_cycle.get('fresh_linkage_included')}`",
        f"- fresh_production_valid_matched: `{latest_cycle.get('fresh_production_valid_matched')}`",
    ]
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description="Render markdown runtime status snapshot.")
    parser.add_argument(
        "--output",
        default="Documentation/GENERATED_RUNTIME_STATUS_SNAPSHOT.md",
        help="Output markdown path relative to repo root",
    )
    args = parser.parse_args()
    output = ROOT / args.output
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(build_snapshot(), encoding="utf-8")
    print(str(output))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
